### ISSUE TITLE
Added "transform: scale" for IE 6 – 8

### ISSUE THREAD

**Issue by ingozoell** [justincavery/am-i-responsive#2]
Hi, great tool! 

I added some code to make "transform: scale" work in IE 6 – 8, too (tested in IE 7 and 8).

``` HTML
<!-- index.html 
Add "transform: scale" for IE 6 – 8 via http://www.useragentman.com/IETransformsTranslator/ -->
```

``` CSS
<!--[if IE 8]>
<style> 

.desktop iframe {
    -ms-filter: "progid:DXImageTransform.Microsoft.Matrix(M11=0.3181, M12=0, M21=0, M22=0.3181, SizingMethod='auto expand')";
}

.laptop iframe {
    -ms-filter: "progid:DXImageTransform.Microsoft.Matrix(M11=0.277, M12=0, M21=0, M22=0.277, SizingMethod='auto expand')";
}

.tablet iframe {
    -ms-filter: "progid:DXImageTransform.Microsoft.Matrix(M11=0.234, M12=0, M21=0, M22=0.234, SizingMethod='auto expand')";
}

.mobile iframe {
    -ms-filter: "progid:DXImageTransform.Microsoft.Matrix(M11=0.219, M12=0, M21=0, M22=0.219, SizingMethod='auto expand')";
}

</style>
<![endif]-->    


<!--[if lte IE 7]>
<style>

.desktop iframe {
    filter: progid:DXImageTransform.Microsoft.Matrix(
    M11=0.3181,
    M12=0,
    M21=0,
    M22=0.3181,
    SizingMethod='auto expand');
}

.laptop iframe { 
    filter: progid:DXImageTransform.Microsoft.Matrix(
    M11=0.277,
    M12=0,
    M21=0,
    M22=0.277,
    SizingMethod='auto expand');
}

.tablet iframe {
    filter: progid:DXImageTransform.Microsoft.Matrix(
    M11=0.234,
    M12=0,
    M21=0,
    M22=0.234,
    SizingMethod='auto expand');
}


.mobile iframe {
    filter: progid:DXImageTransform.Microsoft.Matrix(
    M11=0.219,
    M12=0,
    M21=0,
    M22=0.219,
    SizingMethod='auto expand');
}

</style>
<![endif]-->
```
